#!/usr/bin/env bash

MODE=${1}
CUSTOMER=${2}

[[ $# -lt 2 ]] && { echo "usage: $0 [apply, delete] CUSTOMER" ; exit ;}

# templating the secret for the private ssh key
docker run -i --rm \
    -v $(pwd)/manifests:/manifests \
    -v $(pwd)/../3141-customers/${CUSTOMER}/.ssh:/.ssh \
    300481/render:v0.1.3 \
    --var keyfile=/.ssh/id_rsa \
    --in /manifests/secret.yaml.tmpl \
    --out /manifests/secret.yaml

apply() {
    # install the daemonset
    docker run -i --rm \
        -v $(pwd)/../3141-customers/${CUSTOMER}:/data \
        -v $(pwd)/manifests:/manifests \
        300481/kubectl:v1.14.3 \
        apply -f /manifests/*.yaml
}

delete() {
    # decommission the daemonset
    docker run -i --rm \
        -v $(pwd)/../3141-customers/${CUSTOMER}:/data \
        -v $(pwd)/manifests:/manifests \
        300481/kubectl:v1.14.3 \
        delete -f /manifests/*.yaml
}

case ${MODE} in
    apply)
        apply
        ;;
    delete)
        delete
        ;;
    *)
        echo "usage: $0 [apply, delete] CUSTOMER"
        ;;
esac