#!/usr/bin/env bash

MODE=${1}
CUSTOMER=${2}

SELF_DIR=$(readlink -f $(dirname $0))

[[ $# -lt 2 ]] && { echo "usage: $0 [apply, delete] CUSTOMER" ; exit ;}

# templating the secret for the private ssh key
docker run -i --rm \
    -v ${SELF_DIR}/manifests:/manifests \
    -v ${SELF_DIR}/../3141-customers/${CUSTOMER}/.ssh:/.ssh \
    300481/render:v0.1.3 \
    --var keyfile=/.ssh/id_rsa \
    --var ruaversion=$(< ${SELF_DIR}/VERSION) \
    --indir /manifests/templates/ \
    --outdir /manifests/

apply() {
    # install the daemonset
    docker run -i --rm \
        -v ${SELF_DIR}/../3141-customers/${CUSTOMER}:/data \
        -v ${SELF_DIR}/manifests:/manifests \
        300481/kubectl:v1.14.3 \
        apply -f /manifests/
}

delete() {
    # decommission the daemonset
    docker run -i --rm \
        -v ${SELF_DIR}/../3141-customers/${CUSTOMER}:/data \
        -v ${SELF_DIR}/manifests:/manifests \
        300481/kubectl:v1.14.3 \
        delete -f /manifests/
}

case ${MODE} in
    apply)
        apply
        ;;
    delete)
        delete
        ;;
    *)
        echo "usage: $0 [apply, delete] CUSTOMER"
        ;;
esac