apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alpine
  namespace: kube-system
  labels:
    app: alpine
spec:
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: 300481/rua:v0.1.1
        name: rua
        command: ["sleep"]
        args: ["100000"]
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: privatekey
          mountPath: /root/ssh/id_rsa
          subPath: id_rsa
        - name: hostkey
          mountPath: /root/hostkeys
      volumes:
      - name: privatekey
        secret:
          secretName: privatekey
          defaultMode: 0600
      - name: hostkey
        hostPath:
          path: /etc/ssh